### ISSUE TITLE
wiki: fix docker run commands

### ISSUE THREAD

**Issue by mondkaefer** [Neuroimaging-RG/BIDS_conversion#1]
I think there are 3 small problems with the docker run commands on the wiki:

1. "-c dm2niix" should probably be "-c dcm2niix"
2. On 2 occasions there is a white space missing before the -o parameter: "...niix-o /data/output"
3. Throughout the wiki page you use PQC_ADPRC_20170925 as dicom folder, except for the very last docker run command where it's ADPRC_0080_F0. This should probably be consistent.

**Comment by CatherineMorganII** [comment]
thanks Martin, all fixed!
